"""Policy tests: hashed lock file and Dockerfile supply-chain invariants."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCK_FILE = REPO_ROOT / "promt_engine_service" / "requirements_prod.lock"
DOCKERFILE = REPO_ROOT / "promt_engine_service" / "Dockerfile"


def test_lock_file_exists() -> None:
    assert LOCK_FILE.exists(), "requirements_prod.lock is missing"


def test_lock_file_has_hashes() -> None:
    content = LOCK_FILE.read_text()
    assert "--hash=sha256:" in content, "lock file must contain sha256 hashes"


def test_lock_file_pins_fastapi_m8() -> None:
    content = LOCK_FILE.read_text()
    assert "fastapi-m8" in content, "lock must pin fastapi-m8"


def test_lock_file_pins_auth_sdk_m8() -> None:
    content = LOCK_FILE.read_text()
    assert "auth-sdk-m8" in content, "lock must pin auth-sdk-m8"


def test_lock_file_autogenerated_header() -> None:
    content = LOCK_FILE.read_text()
    assert "pip-compile" in content, "lock must carry pip-compile header"


def test_dockerfile_prod_path_uses_require_hashes() -> None:
    content = DOCKERFILE.read_text()
    assert "--require-hashes" in content, "Dockerfile prod install must use --require-hashes"


def test_dockerfile_prod_install_uses_lock() -> None:
    content = DOCKERFILE.read_text()
    assert "requirements_prod.lock" in content, "Dockerfile prod install must reference requirements_prod.lock"


def test_dockerfile_from_stages_digest_pinned() -> None:
    content = DOCKERFILE.read_text()
    from_lines = [ln.strip() for ln in content.splitlines() if ln.strip().upper().startswith("FROM")]
    assert from_lines, "Dockerfile must have FROM directives"
    for line in from_lines:
        if "scratch" in line.lower() or "AS" in line and "@sha256:" not in line and "FROM --platform" not in line:
            pass
        # Every non-scratch FROM must include a digest pin
        if "scratch" not in line.lower():
            assert "@sha256:" in line, f"FROM stage not digest-pinned: {line}"
